=== tonin-corbas/Class/2a Evaluación/tarea_15/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "nombre": {
          "type": "string"
        },
        "id": {
          "type": "number"
        },
        "disponible": {
          "type": "boolean"
        },
        "urlImagen": {
          "type": "string",
            "format": "uri"
        },
         "fecha": {
          "type" : "string",
            "format": "date"
        }
      },
        "requiered": ["nombre", "id","disponible","urlImagen"]
    }
  }

=== tonin-corbas/Class/2a Evaluación/tarea_15/juegos.json
[{
    "nombre": "elemento",
    "id": 1,
    "disponible": true,
    "urlImagen": "https://user-images.githubusercontent.com/6848427/126122608-f91499ec-3d1f-4792-8e5b-6b46f3dc8b32.png",
  	"fecha": "2005-11-12"
  },
  {
    "nombre":"elemento 2",
    "id": 2,
    "disponible": false,
    "urlImagen":"https://user-images.githubusercontent.com/6848427/126122608-f91499ec-3d1f-4792-8e5b-6b46f3dc8b32.png"
  },
  {
    "nombre": "elemento 3",
    "id": 3,
    "disponible": true,
    "urlImagen": "https://user-images.githubusercontent.com/6848427/126122608-f91499ec-3d1f-4792-8e5b-6b46f3dc8b32.png",
    "fecha": "2000-11-01"
  },
  {
    "nombre": "elemento 4",
    "id": 4,
    "disponible": true,
    "urlImagen": "https://user-images.githubusercontent.com/6848427/126122608-f91499ec-3d1f-4792-8e5b-6b46f3dc8b32.png"
  },
  {
    "nombre": "elemento 5",
    "id": 5,
    "disponible": false,
    "urlImagen": "https://user-images.githubusercontent.com/6848427/126122608-f91499ec-3d1f-4792-8e5b-6b46f3dc8b32.png",
    "fecha": "1975-09-08"
  }
]
